format = """
$directory\
$git_branch\
$git_state\
$time\
$cmd_duration\
$character
"""

add_newline = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[time]
disabled = false
format = '[$time]($style) '
time_format = "%H%M"

[cmd_duration]
disabled = false
min_time = 500
format = 'took [$duration](bold yellow) '
