[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors.normal]
black = "#000000"
red = "#C51E14"
green = "#1DC121"
yellow = "#C7C329"
blue = "#0A2FC4"
magenta = "#C839C5"
cyan = "#20C5C6"
white = "#C7C7C7"

[colors.primary]
background = "#000000"
foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
